name: DeployTest
on: 
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test with echo
        run: echo GITHUB_REF
#         run: echo ${{format(env.SLACK_MSG, 'test', GITHUB_REF, 'test')}}
        env:
          SLACK_MSG: >
            {{'name':'{0}', 'version':'{1}','version_url':'https://github.com/githubactiontest/releases/tag/{1}','status':':rocket: Successful Deployment :rocket:','server':'{2}'}}
#       - name: Notify Slack of successful deployment
#         id: slack
#         uses: slackapi/slack-github-action@v1.15.0
#         with:
#           payload: ${{format(env.SLACK_MSG, 'test', GITHUB_REF, 'test' )}}
#         env:
#           SLACK_WEBHOOK_URL: https://hooks.slack.com/workflows/redacted
#           SLACK_MSG: >
#             {{"name":"{0}", "version":"{1}","version_url":"https://github.com/githubactiontest/releases/tag/{1}","status":":rocket: Successful Deployment :rocket:","server":"{2}"}}
